name: ESLint

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 21.7
      uses: actions/setup-node@v2
      with:
        node-version: '21.7'

    - name: Run ESLint
      run: npm run lint
